#ifndef THRUST_H
#define THRUST_H

#include <memory>
#include <numeric>
#include <vector>

#include "vector3.h"
#include "Thrust/iThrust.h"
#include "Thrust/BasicMainEngineModel.h"
#include "Thrust/FuelStateStruct.h"
#include "Thrust/ME_thrustState.h"
#include "Thrust/EngineConfig.h"
#include "Thrust/FueltankStruct.h"

/**
 * @brief Enumeration of propulsion system types used for thrust queries.
 *
 * Defines the selectable propulsion subsystems within the simulation framework.
 * This enumeration is used to specify whether thrust-related functions should
 * return the contribution of a specific propulsion system or the combined
 * effect of all available systems.
 */
enum class EngineType
{
    /**
     * @brief Combined contribution of all propulsion systems.
     *
     * Represents the total thrust generated by all active propulsion subsystems,
     * including the main engine and the reaction control system.
     */
    All,

    /**
     * @brief Main engine propulsion system.
     *
     * Refers to the primary propulsion unit responsible for generating the
     * dominant thrust along the vehicle's main thrust axis.
     */
    MainEngine,

    /**
     * @brief Reaction Control System (RCS).
     *
     * Refers to the set of smaller thrusters used for attitude control and
     * fine translational maneuvers. The resulting thrust is typically modeled
     * as a vector quantity.
     */
    RCS
};

/**
 * @class Thrust
 * @brief Propulsion orchestrator of the spacecraft.
 *
 * This class no longer represents a single engine. Instead, it acts as the
 * central propulsion manager for the spacecraft and coordinates:
 *
 * - multiple engine models
 * - multiple propellant tanks
 * - thrust target dispatching
 * - engine activation / deactivation
 * - aggregated thrust computation
 * - global fuel bookkeeping
 *
 * Each engine is represented by an implementation of @ref IThrustModel and is
 * stored internally in the propulsion system. The class combines the individual
 * engine outputs into a single resulting thrust vector that can be passed to
 * the physics simulation.
 *
 * The propulsion system also owns the available fuel tanks. Each engine may
 * consume propellant from an assigned tank. This enables future support for
 * multi-tank and subsystem-specific fuel architectures, e.g.:
 *
 * - main engine tank
 * - attitude control / RCS tank
 * - reserve tank
 *
 * Current scope:
 * - multi-engine support
 * - 3D thrust vector aggregation
 * - multiple fuel tanks
 *
 * Future scope:
 * - engine groups
 * - tank authorization / routing
 * - crossfeed systems
 * - engine failure simulation
 */
class Thrust
{
public:

    /**
     * @brief Default constructor.
     *
     * Creates an empty propulsion system without engines and without tanks.
     * Engines and tanks must be initialized later via @ref initializeEngines.
     */
    Thrust();

    /**
     * @brief Default destructor.
     */
    ~Thrust();

    /**
     * @brief Advances the complete propulsion system by one simulation step.
     *
     * This function updates all registered engines and applies their fuel
     * consumption to the assigned tanks.
     *
     * Responsibilities:
     * - propagate engine dynamics in discrete time
     * - update actual thrust values from target thrust commands
     * - reduce fuel in the assigned tanks
     * - keep the propulsion system state consistent
     *
     * The individual engine models typically use a first-order response model:
     *
     * \f[
     * T(t+\Delta t) = T(t) + \frac{\Delta t}{\tau}\left(T_{target} - T(t)\right)
     * \f]
     *
     * where:
     * - \f$T\f$ is the current thrust
     * - \f$T_{target}\f$ is the commanded thrust
     * - \f$\tau\f$ is the engine time constant
     * - \f$\Delta t\f$ is the simulation time step
     *
     * If no fuel is available, the propulsion system does not advance thrust
     * production.
     *
     * @param dt Simulation time step [s]
     */
    void updateThrust(double dt);

    // -------------------------------------------------------------------------
    // Public setter functions
    // -------------------------------------------------------------------------

    /**
     * @brief Initializes engines and fuel tanks of the propulsion system.
     *
     * This function creates the internal engine models from the supplied engine
     * configurations and registers the available fuel tanks.
     *
     * The engine list may contain an arbitrary number of engines. This enables
     * spacecraft configurations such as:
     * - single main engine
     * - main engine + attitude thrusters
     * - multi-engine propulsion clusters
     *
     * The tank list may also contain multiple tanks. Each value in the vector
     * represents the initial mass or capacity of one tank.
     *
     * @param engines Vector of engine configurations
     * @param tanks Vector of tank masses / capacities [kg]
     */
    void initializeEngines(std::vector<EngineConfig> &engines, const std::vector<FuelTank> &tanks);

    /**
     * @brief Activates a specific engine.
     *
     * @param engineNr Index of the engine to activate
     */
    void activateEngine(const size_t &engineNr);

    /**
     * @brief Deactivates a specific engine.
     *
     * @param engineNr Index of the engine to deactivate
     */
    void deactivateEngine(const size_t &engineNr);

    /**
     * @brief Deactivates all engines.
     */
    void turnOffAllEngines();

    /**
     * @brief Sets a new target thrust for a specific engine.
     *
     * @param tThrust Target thrust [N]
     * @param engineNr Index of the engine to command
     */
    void setTargetThrustInNewton(EngineType engine, const double &tMainEngineThrust = 0.0, const Vector3 &tRCSThrust = {0.0, 0.0, 0.0});

    /**
     * @brief Sets a new target thrust for a specific engine in normalized form.
     *
     * The input value is interpreted as a fraction of the engine's maximum
     * thrust capability.
     *
     * Main engine thrust is incoming as a double value. Thrust for RCS engines are
     * in vectorized form. The parameter EngineType is necessary for the model
     * routing descision.
     *
     * @param tThrustInPercentage Normalized thrust command [0..1]
     * @param engineNr Index of the engine to command
     */
    void setTargetThrustInPercentage(EngineType engine, const double &tMainEngineThrust = 0.0, const Vector3 &tRCSThrust = {0.0, 0.0, 0.0});

    /**
     * @brief Sets target thrust to zero for all engines.
     *
     * Can be used after landing, in emergency situations, or as part of a
     * general propulsion shutdown.
     */
    void shutDownAllEngines() const;

    // -------------------------------------------------------------------------
    // Public getter functions
    // -------------------------------------------------------------------------

    /**
     * @brief Returns the commanded target thrust vector.
     *
     * Depending on the selected engine type, this function returns either the
     * combined target thrust of all propulsion subsystems or the target thrust
     * of a specific subsystem.
     *
     * @param engine Specifies the propulsion subsystem to query. If set to
     * EngineType::All (default), the total target thrust is returned.
     *
     * @return Commanded thrust vector [N]
     */
    Vector3 getTargetThrust(EngineType engine = EngineType::All) const;

    /**
     * @brief Returns the current thrust vector.
     *
     * Depending on the selected engine type, this function returns either the
     * total thrust generated by all active propulsion subsystems or the
     * contribution of a specific subsystem.
     *
     * The returned thrust reflects actuator dynamics, allocation effects,
     * and physical limitations of the propulsion system.
     *
     * @param engine Specifies the propulsion subsystem to query. If set to
     * EngineType::All (default), the total thrust is returned.
     *
     * @return Resulting thrust vector [N]
     */
    Vector3 getCurrentThrust(EngineType engine = EngineType::All) const;

    /**
     * @brief Returns the current thrust in normalized form.
     *
     * Depending on the selected engine type, this function returns either the
     * normalized total thrust or the normalized thrust contribution of a
     * specific subsystem.
     *
     * The returned vector represents the thrust components relative to the
     * maximum available thrust authority of the selected propulsion system.
     *
     * @param engine Specifies the propulsion subsystem to query. If set to
     * EngineType::All (default), the total normalized thrust is returned.
     *
     * @return Normalized thrust vector [%]
     */
    Vector3 getCurrentThrustInPercentage(EngineType engine = EngineType::All) const;

    /**
     * @brief Returns the questioned direction of thrust as a normalized factor
     * @param EngineType type of requested engine
     * @param engineID ID of requested engine typically 0 is related to mainengine
     * @return Normalized Direction of thrust
     */
    Vector3 getDirectionOfThrust(EngineType engine = EngineType::MainEngine, int engineID = 0) const;

    /**
     * @brief Returns the total current fuel consumption of all engines.
     *
     * @return Total propellant mass flow rate [kg/s]
     */
    double getFuelConsumption(EngineType engine = EngineType::All) const;

    /**
     * @brief Computes the total remaining fuel mass over all tanks.
     *
     * @return Sum of all tank masses [kg]
     */
    double getFuelMassOfAllTanks() const;

    /**
     * @brief Returns access to all fuel tanks of the spacecraft.
     *
     * Provides a read-only reference to the internal list of fuel tanks.
     * Each tank contains its own state information, such as current mass,
     * capacity, and usage.
     *
     * This replaces the previous aggregated fuel mass interface, allowing
     * more flexible handling of multiple tank systems (e.g., main tank,
     * RCS tank, or future crossfeed configurations).
     *
     * The caller can iterate over all tanks to compute derived values such as:
     * - total remaining propellant mass
     * - per-system fuel usage
     * - UI display of individual tank states
     *
     * Access example:
     * @code
     * double totalFuel = 0.0;
     * for(const auto& tank : spacecraft.getFuelTanks()) {
     *     totalFuel += tank.mass;
     * }
     * @endcode
     *
     * @return Constant reference to the vector of fuel tanks.
     */
    const std::vector<FuelTank>& getFuelTanks() const;

private:
    // -------------------------------------------------------------------------
    // Private Member
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // Private Methods
    // -------------------------------------------------------------------------
    /**
     * @brief Internal list of engine models managed by the propulsion system.
     *
     * Each entry represents one concrete engine model implementing
     * @ref IThrustModel.
     */
    std::vector<std::unique_ptr<IThrustModel>> models_;

    /**
     * @brief Internal list of spacecraft fuel tanks.
     *
     * Each tank acts as a propellant reservoir that may be assigned to one or
     * more engines.
     */
    std::vector<FuelTank> tanks_;

    /**
     * @brief Global fuel-related state of the propulsion system.
     *
     * Used for aggregated fuel bookkeeping and telemetry.
     */
    FuelState fuelState_;

    /**
     * @brief Legacy single-engine configuration cache.
     *
     * @note This member may become obsolete in a fully multi-engine
     *       architecture and should be reviewed during future refactoring.
     */
    EngineConfig engineConfig_;

    /**
     * @brief Global thrust-related state of the propulsion system.
     *
     * Used for aggregated propulsion telemetry and backward-compatible access.
     */
    ME_ThrustState ME_thrustState_;

    /**
     * @brief Adds fuel tanks to the propulsion system.
     *
     * Each entry in the vector represents one tank with a given initial fuel
     * mass or capacity.
     *
     * @param tanks Vector of tank masses [kg]
     */
    void addFuelTank(const std::vector<FuelTank> &tanks);

    /**
     * @brief Adds a single engine model to the propulsion system.
     *
     * Ownership of the engine model is transferred to the propulsion system.
     *
     * @param model Engine model instance
     */
    void addModel(std::unique_ptr<IThrustModel> model);
};

#endif
