#ifndef ME_THRUSTSTATE_H
#define ME_THRUSTSTATE_H

#include "vector3.h"

/**
 * @brief Simulation output data associated with the main engine thrust state.
 *
 * This structure represents the commanded and actual thrust of the main engine
 * as used within the simulation framework. It captures the effect of engine
 * dynamics by distinguishing between the requested (target) thrust and the
 * physically generated (current) thrust.
 *
 * All thrust quantities are scalar, as the main engine is assumed to produce
 * thrust along a fixed direction defined by the vehicle configuration.
 */
struct ME_ThrustState
{
    /**
     * @brief Commanded main engine thrust.
     *
     * Represents the desired thrust level provided by the guidance or control
     * system prior to actuator dynamics, saturation, or engine limitations.
     *
     * Unit: N
     */
    double target{0.0};

    /**
     * @brief Actual main engine thrust.
     *
     * Represents the thrust currently generated by the engine after applying
     * the engine dynamic response model.
     *
     * Unit: N
     */
    double current{0.0};

    /**
     * @brief Commanded thrust relative to maximum engine thrust.
     *
     * Expresses the commanded thrust level as a percentage of the maximum
     * available main engine thrust.
     *
     * Unit: %
     */
    double targetPercentage{0.0};

    /**
     * @brief Current Thrust direction
     *
     * Represents the thrust direction. Normally this direction is fixed. Nevertheless it
     * could become a state, when thrust vectorizing is implemented.
     *
     * Unit: [-]
     */
    Vector3 direction{0.0, 0.0, 0.0};
};

#endif // ME_THRUSTSTATE_H
