#pragma once

#include <Eigen/Dense>

#include <iostream>
#include <string>

/**
 * @brief Simulation output data associated with a single Reaction Control System (RCS) thruster.
 *
 * This structure represents the dynamic runtime state of one individual RCS
 * engine as used inside the propulsion subsystem.
 *
 * The physical thrust vector is not stored directly as force output. Instead,
 * the scalar thrust magnitude is combined with the thrust direction vector by
 * the Thrust Orchestrator when generating the final spacecraft force and torque.
 *
 * The structure intentionally separates:
 * - static engine configuration (stored in RCSEngineConfig)
 * - dynamic runtime state (stored here)
 *
 * To maintain traceability between telemetry, cockpit visualization, data
 * export, and propulsion configuration, the structure additionally contains
 * lightweight engine metadata such as ID, engine name, axis assignment, and
 * thrust direction.
 */
struct RCS_ThrustState
{
    // -------------------------------------------------------------------------
    // Engine metadata
    // -------------------------------------------------------------------------

    /**
     * @brief Unique identifier of the represented RCS engine.
     *
     * The ID corresponds to the engine definition inside the spacecraft
     * configuration.
     *
     * Default value:
     * -1 = invalid / uninitialized engine ID
     *
     * Unit: -
     */
    int engineID{-1};

    /**
     * @brief Human-readable name of the represented RCS engine.
     *
     * Example:
     * - "RCS_PosX"
     * - "RCS_NegYaw"
     */
    std::string engineName{};

    /**
     * @brief Controlled translation or rotation axis of the RCS engine.
     *
     * Examples:
     * - "+x"
     * - "-y"
     * - "+yaw"
     *
     * Unit: -
     */
    std::string axis{};

    /**
     * @brief Normalized thrust SBF_direction vector of the RCS engine.
     *
     * Represents the thrust SBF_direction in spacecraft body coordinates.
     *
     * The SBF_direction is typically constant for fixed thrusters but may become
     * dynamic in future thrust-vectoring implementations.
     *
     * Unit: -
     */
    Eigen::Vector3d SBF_direction{0.0, 0.0, 0.0};

    // -------------------------------------------------------------------------
    // Dynamic runtime state
    // -------------------------------------------------------------------------

    /**
     * @brief Actual scalar thrust magnitude generated by the RCS thruster.
     *
     * Represents the physically generated thrust after command delay,
     * actuator dynamics, and saturation effects have been applied.
     *
     * The corresponding thrust vector is generated externally by combining
     * this scalar magnitude with the engine thrust direction vector.
     *
     * Unit: N
     */
    double currentThrust{0.0};

    /**
     * @brief Commanded scalar thrust magnitude.
     *
     * Represents the desired thrust requested by the controller or user input
     * before actuator dynamics are applied.
     *
     * Unit: N
     */
    double targetThrust{0.0};

    /**
     * @brief Commanded thrust level relative to maximum available thrust.
     *
     * Typical values:
     * - 0.0 = thruster inactive
     * - 1.0 = maximum commanded thrust
     *
     * The BasicRCSModel currently operates as a binary actuator model,
     * therefore only values close to 0 or 1 are expected.
     *
     * Unit: -
     */
    double targetThrustPercentage{0.0};

    /**
     * @brief Maximum thrust provided by specific engine
     *
     * Unit: N
     */
    double maxThrust{0.0};

    /**
     * @brief Internal normalized actuator state.
     *
     * Represents the current dynamic state of the thruster actuator and thrust
     * buildup model.
     *
     * Typical range:
     * - 0.0 = no generated thrust
     * - 1.0 = nominal steady-state thrust
     *
     * Unit: -
     */
    double thrustState{0.0};

    /**
     * @brief Current fuel consumption rate of the engine.
     *
     * Represents the instantaneous propellant mass flow consumed by the engine
     * at its current operating state. The value is used to determine the
     * propellant mass reduction over a simulation timestep.
     *
     * The consumed propellant mass is given by:
     *
     * \f[
     * \Delta m = \dot{m} \Delta t
     * \f]
     *
     * where:
     * - \f$\dot{m}\f$ is the consumption rate [kg/s]
     * - \f$\Delta t\f$ is the simulation timestep [s]
     * - \f$\Delta m\f$ is the consumed propellant mass [kg]
     *
     * @note A value of zero indicates that no propellant is currently consumed.
     */
    double consumptionRate{0.0};

    /**
     * @brief Current torque generated by the RCS thruster.
     *
     * The torque is expressed in the spacecraft body-fixed frame (SBF) and
     * is computed from the thruster position relative to the spacecraft's
     * center of mass and the current thrust force. This quantity is used by
     * the rotational dynamics model to compute the resulting angular
     * acceleration.
     */
    Eigen::Vector3d SBF_currentTorque{0.0, 0.0, 0.0};
};
