#pragma once

#include "vector3.h"

/**
 * @brief Simulation output data associated with the Reaction Control System (RCS).
 *
 * This structure represents the current and commanded thrust states of the RCS
 * as used within the simulation framework. The RCS thrust is expressed as a
 * vector quantity, allowing representation of combined effects of multiple
 * thrusters after allocation and actuator dynamics.
 *
 * All vector quantities must be defined consistently in the same reference
 * frame (e.g., body frame or ENU frame) as used by the vehicle dynamics model.
 */
struct RCS_ThrustState
{
    /**
     * @brief Actual RCS thrust vector.
     *
     * Represents the resulting thrust vector generated by the RCS after
     * actuator dynamics, allocation, and physical limitations have been applied.
     *
     * Unit: N
     */
    Vector3 currentThrust{};

    /**
     * @brief Commanded RCS thrust vector.
     *
     * Represents the desired thrust vector provided by the control system
     * prior to actuator dynamics, saturation effects, or allocation constraints.
     *
     * Unit: N
     */
    Vector3 targetThrust{};

    /**
     * @brief Commanded RCS thrust expressed as percentage of available authority.
     *
     * Each component corresponds to the commanded thrust relative to the maximum
     * achievable thrust along the respective axis. The definition of the maximum
     * thrust authority depends on the RCS configuration and allocation strategy.
     *
     * Unit: %
     */
    Vector3 targetThrustPercentage{};
};
