#pragma once

#include <Eigen/Dense>

/**
 * @file FlightCommandDTO.h
 * @brief Defines the frontend-facing flight command data transfer object.
 */

/**
 * @struct FlightCommandDTO
 * @brief Transfers user flight commands from the frontend to the simulation interface.
 *
 * This structure represents control input generated by the frontend, such as
 * keyboard, UI or controller input. It is passed to the telemetry/interface
 * layer, where it can be translated into backend-specific command structures.
 *
 * The DTO intentionally contains plain data only and must not implement
 * command arbitration, control logic or simulation behavior.
 *
 * Typical usage:
 * - Populated by frontend input systems
 * - Forwarded to the interface layer
 * - Translated by the mapper into backend control commands
 *
 * @note Units and ranges must be interpreted consistently by the receiving
 *       simulation backend. This DTO does not enforce constraints.
 */
struct FlightCommandDTO
{
    /**
     * @brief Main engine thrust command.
     *
     * Represents the commanded main engine thrust level.
     *
     * @note Expected range: [0.0, 100.0] as percentage.
     */
    float mainEngine = 0.0f;

    /**
     * @brief Rotational command.
     *
     * Represents desired rotational input around the spacecraft principal axes.
     *
     * Components:
     * - x: pitch
     * - y: yaw
     * - z: roll
     */
    Eigen::Vector3d rotation = {0.0, 0.0, 0.0};

    /**
     * @brief Translational command.
     *
     * Represents desired translational input along the spacecraft principal axes.
     *
     * Components:
     * - x: lateral movement
     * - y: vertical movement
     * - z: longitudinal movement
     */
    Eigen::Vector3d translation = {0.0, 0.0, 0.0};

    /**
     * @brief Stabilization request flag.
     *
     * Requests attitude stabilization when enabled.
     */
    bool stabilize = false;

    /**
     * @brief Kill rotation request flag.
     *
     * Requests damping of rotational motion when enabled.
     */
    bool killRotation = false;

    /**
     * @brief Autopilot activation flag.
     *
     * Requests activation of the autopilot command path when enabled.
     */
    bool autopilotActive = false;
};
