#pragma once

#include <QString>

/**
 * @brief Frontend telemetry representation of a single RCS thruster.
 *
 * This structure represents the reduced runtime telemetry of one individual
 * Reaction Control System (RCS) engine as transferred from the simulation
 * backend to the cockpit frontend.
 *
 * The structure is intentionally frontend-oriented and independent from the
 * internal backend propulsion model implementation. It is designed for:
 * - cockpit visualization
 * - telemetry rendering
 * - frontend-side state management
 * - future middleware transport (e.g. ROS messages)
 *
 * Only lightweight telemetry and identification data required by the UI are
 * included. Static propulsion configuration and backend-specific simulation
 * logic remain encapsulated inside the backend domain model.
 */
struct RCSCockpitTelemetry
{
    /**
     * @brief Unique identifier of the represented RCS engine.
     *
     * The ID corresponds to the engine definition inside the backend
     * spacecraft configuration.
     *
     * Default value:
     * -1 = invalid or uninitialized engine ID
     *
     * Unit: -
     */
    int engineID{-1};

    /**
     * @brief Human-readable name of the represented RCS engine.
     *
     * Example:
     * - "RCS_PosX"
     * - "RCS_NegYaw"
     */
    QString name{};

    /**
     * @brief Controlled translation or rotation axis of the RCS engine.
     *
     * Examples:
     * - "+x"
     * - "-y"
     * - "+yaw"
     *
     * Unit: -
     */
    QString axis{};

    /**
     * @brief Current scalar thrust magnitude generated by the RCS engine.
     *
     * Represents the physically generated thrust after actuator dynamics,
     * command delay, and saturation effects have been applied.
     *
     * Unit: N
     */
    double currentThrust{0.0};

    /**
     * @brief Commanded scalar target thrust magnitude.
     *
     * Represents the desired thrust requested by the controller or user input
     * before actuator dynamics are applied.
     *
     * Unit: N
     */
    double targetThrust{0.0};

    /**
     * @brief Internal normalized actuator state of the RCS thruster.
     *
     * Represents the current actuator response state used by the propulsion
     * model.
     *
     * Typical range:
     * - 0.0 = thruster inactive
     * - 1.0 = full steady-state response
     *
     * Unit: -
     */
    double actuatorState{0.0};
};
