#ifndef TELEMETRYDTO_H
#define TELEMETRYDTO_H

#include <Eigen/Dense>
#include <QVector>
#include <QString>

/**
 * @brief Frontend telemetry data transfer object.
 *
 * This structure represents the frontend-facing telemetry snapshot used by the
 * user interface to visualize the current simulation state.
 *
 * Telemetry is generated from the backend simulation state (SimData) through a
 * dedicated translation layer and intentionally remains independent from the
 * backend domain model.
 *
 * The structure contains presentation-oriented data grouped by functional
 * subsystems such as navigation, mission context, propulsion systems,
 * structural integrity and sensors.
 *
 * This DTO is designed for:
 * - Qt signal/slot communication
 * - User interface updates
 * - Telemetry visualization
 * - Telemetry export and recording
 *
 * The DTO intentionally contains plain data only and must not implement
 * simulation logic.
 */
struct Telemetry
{
    /**
     * @brief Current simulation time in seconds.
     */
    double time{0.0};

    /**
     * @brief Navigation telemetry.
     *
     * Contains the primary spacecraft state required for guidance, navigation
     * and control visualization.
     */
    struct Navigation
    {
        Eigen::Vector3d MCI_position{0.0, 0.0, 0.0};            ///< Spacecraft position in Moon-Centered Inertial frame.
        Eigen::Vector3d MCI_velocity{0.0, 0.0, 0.0};            ///< Spacecraft velocity in Moon-Centered Inertial frame.
        Eigen::Quaterniond IB_Orientation{1.0, 0.0, 0.0, 0.0};  ///< Spacecraft attitude quaternion from inertial frame to body frame.
        Eigen::Vector3d SBF_AngularVelocity{0.0, 0.0, 0.0};     ///< Angular velocity expressed in Spacecraft Body Frame.
    };

    /**
     * @brief Mission-specific reference information.
     *
     * Contains landing site definitions represented in multiple coordinate
     * systems.
     */
    struct MissionContext
    {
        /**
         * @brief Surface coordinate representation using latitude, longitude and altitude.
         */
        struct SurfaceCoordinates
        {
            double latitude{0.0};  ///< Latitude in radians.
            double longitude{0.0}; ///< Longitude in radians.
            double altitude{0.0};  ///< Altitude above lunar reference radius in meters.
        };

        /**
         * @brief Position-only state in a Cartesian reference frame.
         *
         * Used for static mission reference points such as landing sites.
         */
        struct PositionState
        {
            Eigen::Vector3d position{0.0, 0.0, 0.0}; ///< Position vector.
        };

        SurfaceCoordinates MSC_LandingSite; ///< Landing site in Moon Surface Coordinates.
        PositionState MCMF_landingSite;     ///< Landing site position in Moon-Centered Moon-Fixed frame.
        PositionState MCI_landingSite;      ///< Landing site position in Moon-Centered Inertial frame.
    };

    /**
     * @brief Spacecraft state expressed in various coordinate systems.
     *
     * This section provides the current spacecraft state transformed into
     * commonly used reference frames for analysis and visualization.
     */
    struct FrameContext
    {
        /**
         * @brief Position and velocity state in a Cartesian reference frame.
         */
        struct State
        {
            Eigen::Vector3d position{0.0, 0.0, 0.0}; ///< Position vector.
            Eigen::Vector3d velocity{0.0, 0.0, 0.0}; ///< Velocity vector.
        };

        State MCI_State;  ///< State in Moon-Centered Inertial frame.
        State MCMF_State; ///< State in Moon-Centered Moon-Fixed frame.
        State ENU_State;  ///< State in local East-North-Up frame.
        State LVLH_State; ///< State in Local Vertical Local Horizontal frame.

        MissionContext::SurfaceCoordinates MSC_State; ///< State represented as Moon Surface Coordinates.
    };

    /**
     * @brief Spacecraft structural status information.
     */
    struct HullIntegrity
    {
        bool spacecraftIntegrity{true}; ///< True if the spacecraft is structurally intact.
        QString spacecraftState{};      ///< Human-readable spacecraft state.
    };

    /**
     * @brief Runtime messages generated by the simulation.
     */
    struct Console
    {
        QString output{}; ///< Console output message.
    };

    /**
     * @brief Propulsion system telemetry.
     *
     * Contains telemetry for the main engine, reaction control system thrusters
     * and propellant tanks.
     */
    struct PropulsionSystems
    {
        /**
         * @brief Main engine thrust telemetry.
         */
        struct MainEngineThrust
        {
            double T_target{0.0};                           ///< Commanded target thrust in newtons.
            double T_current{0.0};                          ///< Current actual thrust in newtons.
            double T_targetPercentage{0.0};                 ///< Target thrust percentage.
            Eigen::Vector3d SBF_direction{0.0, 0.0, 0.0};   ///< Thrust direction in SBF.
        };

        /**
         * @brief Reaction Control System thruster telemetry.
         */
        struct RCSThrust
        {
            int engineID{-1};              ///< Unique thruster identifier.
            QString engineName{};          ///< Human-readable thruster name.
            QString axis{};                ///< Controlled axis or role.
            Eigen::Vector3d SBF_direction{0.0, 0.0, 0.0}; ///< Thrust direction in SBF.
            double T_current{0.0};         ///< Current thrust in newtons.
            double T_target{0.0};          ///< Target thrust in newtons.
            double thrustState{0.0};       ///< Normalized or discrete thrust state.
        };

        /**
         * @brief Fuel tank telemetry.
         */
        struct Tank
        {
            int ID{-1};              ///< Unique tank identifier.
            QString name{};          ///< Human-readable tank name.
            QString role{};          ///< Tank role, e.g. main propellant or RCS.
            double capacity{0.0};    ///< Maximum tank capacity.
            double mass{0.0};        ///< Current propellant mass.
            double fillLevel{0.0};   ///< Current normalized fill level.
        };

        MainEngineThrust mainEngine;   ///< Main engine telemetry.
        QVector<RCSThrust> RCSEngines; ///< Collection of RCS engine telemetry.
        QVector<Tank> fuelTanks;       ///< Collection of fuel tank telemetry.
    };

    /**
     * @brief Sensor and derived measurement telemetry.
     */
    struct Sensor
    {
        double GLoad{0.0}; ///< Current experienced acceleration load in g.
    };

    Navigation navigation;               ///< Primary navigation telemetry.
    MissionContext missionContext;       ///< Mission context telemetry.
    FrameContext frameContext;           ///< Frame transformation telemetry.
    HullIntegrity hullIntegrity;         ///< Spacecraft integrity telemetry.
    Console console;                     ///< Console output telemetry.
    PropulsionSystems propulsionSystems; ///< Propulsion telemetry.
    Sensor sensor;                       ///< Sensor telemetry.
};

#endif // TELEMETRYDTO_H
